### Alle lesen

GET http://localhost:8080/api/v1/customer?limit=2000 HTTP/1.1

###

GET http://localhost:8080/api/v1/customer?search=Phil&limit=10 HTTP/1.1
###

POST http://localhost:8080/api/v1/customer HTTP/1.1
content-type: application/json

{
    "name": "B Name",
    "code": "A Code",
    "price": 50.0
}

###
POST http://localhost:8080/api/v1/customer/readBenchmark?n=100 HTTP/1.1

###

POST http://localhost:8080/api/v1/customer/init?n=10 HTTP/1.1

###

POST http://localhost:8080/api/v1/customer/updateBenchmark?n=3 HTTP/1.1


###
POST http://localhost:8080/api/v1/customer/deleteBenchmark?n=3 HTTP/1.1