### Alle lesen

GET http://localhost:8080/api/v1/customer?limit=20 HTTP/1.1

###

GET http://localhost:8080/api/v1/customer?search=Phil&limit=10&offset=10 HTTP/1.1
###

POST http://localhost:8080/api/v1/customer HTTP/1.1
content-type: application/json

{
    "name": "B Name",
    "code": "A Code",
    "price": 50.0
}

###

POST http://localhost:8080/api/v1/customer/init?n=1000 HTTP/1.1




###
GET http://10.0.7.71:8080/api/v1/customer?limit=20&offset=0
###
GET http://10.0.7.71:8080/api/v1/customer?limit=2 HTTP/1.1


###
GET http://10.0.7.71:8081/api/v1/customer?limit=2&offset=0
###
POST http://10.0.7.71:8081/api/v1/customer/init?n=10 HTTP/1.1

